[[plugins]]
repo = 'vim-denops/denops.vim'


[[plugins]]
repo        = 'Shougo/ddc.vim'
depends     = ['denops.vim']
hook_add    = '''
call ddc#custom#patch_global('sources', ['around', 'file', 'vim-lsp'])

call ddc#custom#patch_global('ui', 'native')

call ddc#custom#patch_global('sourceParams', #{
      \   around: #{ maxSize: 500 },
      \ })

call ddc#custom#patch_global('sourceOptions', {
      \ '_': {
      \   'matchers': ['matcher_head'],
      \   'sorters': ['sorter_rank']
      \ },
      \ 'around': {
      \   'mark': 'A'
      \ },
      \ 'file': {
      \   'mark': 'F',
      \   'isVolatile': v:true,
      \   'forceCompletionPattern': '\S/\S*',
      \ },
      \ 'vim-lsp': {
      \   matchers: ['matcher_head'],
      \   mark: 'lsp',
      \ },
      \ })

call ddc#custom#patch_filetype(
    \ ['ps1', 'dosbatch', 'autohotkey', 'registry'], {
    \ 'sourceOptions': {
    \   'file': {
    \     'forceCompletionPattern': '\S\/\S*',
    \   },
    \ },
    \ 'sourceParams': {
    \   'file': {
    \     'mode': 'unix',
    \   },
    \ }})

call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-ui-native'
