[[plugins]]
repo        = 'Shougo/deoplete.nvim'
on_event    = 'InsertEnter'
build       = ':UpdateRemotePlugins'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo      = 'autozimu/LanguageClient-neovim'
on_source = ['deoplete.nvim']
build     = 'bash install.sh'
hook_source = '''
  let g:LanguageClient_autoStart      = 1

  let g:LanguageClient_serverCommands = {
    \ 'ruby': ['solargraph', 'stdio'],
  \}
'''
hook_post_source = '''
  call deoplete#custom#var('omni', 'input_patterns', {
    \ 'ruby': ['[^. *\t]\.\w*', '[a-zA-Z_]\w*::'],
  \})
'''

[[plugins]]
repo      = 'junegunn/fzf'
on_source = "LanguageClient-neovim"
