[[plugins]]
repo        = 'Shougo/deoplete.nvim'
on_event    = 'InsertEnter'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
on_source = 'deoplete.nvim'

[[plugin]]
repo  = "mhartington/nvim-typescript"
on_ft = ['typescript']

# [ruby]--------------------------------------------
## knoowlage
# gem install solargraph
# yard gems
# yard config --gem-install-yri

# [sh]--------------------------------------------
## knoowlage
# npm i -g bash-language-server

# [vue]--------------------------------------------
## knoowlage
# npm i -g vue-language-server

# [go]--------------------------------------------
## knoowlage
# go get golang.org/x/tools/cmd/gopls

# [python]--------------------------------------------
## knoowlage
# pip install python-language-server

# [js & ts]--------------------------------------------
## knoowlage
# npm install -g typescript typescript-language-server
