[[plugins]]
repo        = 'Shougo/deoplete.nvim'
on_event    = 'InsertEnter'
build       = ':UpdateRemotePlugins'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo      = 'autozimu/LanguageClient-neovim'
on_source = ['deoplete.nvim']
build     = 'source install.sh'
hook_source = '''
  let g:LanguageClient_autoStart      = 1

  let g:LanguageClient_serverCommands = {
    \ 'ruby':         ['solargraph', 'stdio'],
    \ 'vue':          ['vls'],
    \ 'typescript':   ['typescript-language-server', '--stdio'],
    \ 'javascript':   ['typescript-language-server', '--stdio'],
    \ 'sh':           ['bash-language-server', 'start'],
    \ 'go':           ['gopls', '-mode', 'stdio'],
    \ 'python':       ['pyls'],
  \}

  nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
  nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
  nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
'''
hook_post_source = '''
  call deoplete#custom#var('omni', 'input_patterns', {
    \ 'ruby': ['[^. *\t]\.\w*', '[a-zA-Z_]\w*::'],
  \})
'''

[[plugins]]
repo      = 'junegunn/fzf'
on_source = "LanguageClient-neovim"


# [ruby]--------------------------------------------
## knoowlage
# gem install solargraph
# yard gems
# yard config --gem-install-yri

# [sh]--------------------------------------------
## knoowlage
# npm i -g bash-language-server

# [vue]--------------------------------------------
## knoowlage
# npm i -g vue-language-server

# [go]--------------------------------------------
## knoowlage
# go get golang.org/x/tools/cmd/gopls

# [python]--------------------------------------------
## knoowlage
# pip install python-language-server

# [js & ts]--------------------------------------------
## knoowlage
# npm install -g typescript typescript-language-server
