[[plugins]]
repo      = 'prabirshrestha/vim-lsp'
hook_add  = '''
nm <buffer> <F12>   <plug>(lsp-definition)
nm <buffer> <F11>   <plug>(lsp-peek-definition)
nm <buffer> K       <plug>(lsp-hover)
nm <buffer> <S-F12> <plug>(lsp-references)
nm <buffer> <S-F6>  <plug>(lsp-rename)
nm <buffer> =-      <plug>(lsp-document-format)
nm <buffer> <F2>    <plug>(lsp-type-definition)
'''

[[plugins]]
repo      = 'prabirshrestha/async.vim'

[[plugins]]
repo      = 'mattn/vim-lsp-settings'
