#!/bin/sh
alias vi="vim"
if type nvim &> /dev/null; then
  alias vi="nvim"
  export EDITOR=nvim
fi

# bundler
alias be="bundle exec"
alias bi="bundle install --path vendor/bundle"
alias bil="bundle install --local"
alias bp="bundle package --all"

alias grep='grep --color'
alias mv='mv -i'
alias rm='rm -i'
alias cp='cp -i'
alias df='df -h'

#ls
alias ls='ls -CF'
alias la='ls -CFal --show-control-chars --color=auto'
alias ll='ls -AlFh --show-control-chars --color=auto'
alias lcd=find_cd

alias ps='ps --sort=start_time'
alias ps="ps aux"
alias psp="ps aux | peco"
alias pls=peco-lscd
alias fc="find_cd"
alias color_strip='sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"'

#tmux
alias tchange='tmux set-option -ag prefix C-s'
alias trevert='tmux set-option -ag prefix C-a'

#git
alias ga='git add --all'
alias gc='git commit -m'
alias grf='git reflog --date=local -n 10'
alias gl='git log'
alias gr='git reset --hard'
alias gp='git push origin HEAD'
alias gclone='git clone --recursive'
alias gitsub='git submodule foreach'

# ssh
alias ssh='TERM=xterm; ssh'
